services:
  mongodb:
    image: mongo:8.0
    container_name: siker.im-mongodb
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod
        --auth
        --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: siker.im-redis
    restart: unless-stopped
    expose:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default

  api:
    build: .
    container_name: siker.im-api
    restart: unless-stopped
    ports:
      - "1209:1209"
    volumes:
      - ./app.log:/root/app.log
      - ./.env:/root/.env
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - default

volumes:
  mongo_data:
  redis_data:

networks:
  default:
    driver: bridge
